name: Check and Build Laravel Sail Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Added manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Install dependencies
      run: composer install

    - name: Check for new Laravel Sail version
      id: check_version
      if: github.event_name != 'workflow_dispatch' # Skip version check if manually triggered
      run: |
        CURRENT_VERSION=$(composer show laravel/sail | grep versions | awk '{print $2}')
        LATEST_VERSION=$(composer show laravel/sail --all | grep versions | head -n 1 | awk '{print $2}')
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Update dependencies if new version is available
      if: env.current_version != env.latest_version
      run: composer update laravel/sail

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: vendor/laravel/sail/runtimes/8.4
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/laravel-sail84:latest