name: Check and Build Laravel Sail Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:
  push:
    paths:
        - '.github/workflows/check-and-build.yml'

env:
  REGISTRY: ghcr.io

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Install dependencies
      run: composer install

    - name: Check for new Laravel Sail version
      id: check_version
      if: github.event_name != 'workflow_dispatch' # Skip version check if manually triggered
      run: |
        CURRENT_VERSION=$(composer show laravel/sail | grep versions | awk '{print $2}')
        LATEST_VERSION=$(composer show laravel/sail --all | grep versions | head -n 1 | awk '{print $2}')
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Update dependencies if new version is available
      if: env.current_version != env.latest_version
      run: composer update

    - name: Extract metadata (tags, labels) for Docker
      if: env.current_version != env.latest_version || github.event_name != 'schedule'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/sail-${{ matrix.php-version }}

    - name: Build and push Docker image
      if: env.current_version != env.latest_version || github.event_name != 'schedule'
      uses: docker/build-push-action@v6
      with:
        context: vendor/laravel/sail/runtimes/${{ matrix.php-version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
            WWWGROUP=1000

